name: Build Chrome Profile Manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --noconsole main.py -n chrome_profile_manager ^
            --add-data "profiles.json;." ^
            --add-data "useragents.txt;."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome_profile_manager
          path: dist/chrome_profile_manager.exe
